name: Automation tests

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  test:
    runs-on: macos-13
    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create and start emulator
        run: |
          # avdmanager list device

          echo "y" | sdkmanager "platforms;android-30" "system-images;android-30;google_apis;x86_64"
          echo "no" | avdmanager create avd --force --name nexus --device "pixel_xl" --package "system-images;android-30;google_apis;x86_64" --abi "x86_64"
          $ANDROID_HOME/emulator/emulator -avd nexus -no-audio -no-window -no-snapshot -accel on &

      - name: Wait for emulator to start
        run: |
          until adb shell getprop sys.boot_completed | grep 1; do sleep 1; done
          adb shell input keyevent 82

      - name: Checkout Pet project
        uses: actions/checkout@v4
        with:
          ref: actions

      - name: Install packages
        run: |
          npm ci

      - name: Run test
        run: |
          ls
          npm run wdio
          ls

      - name: Checkout Pet project
        uses: actions/checkout@v4
        with:
          ref: actions

      - name: Run ls
        run: |
          ls

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Deploy 🚀  THIS WORK
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: reports
