name: Automation tests

on:
  pull_request:
    branches: ["main"]

jobs:
  # build:
  #   runs-on: macos-13

  #   steps:
  #     - name: Checkout Pet project
  #       uses: actions/checkout@v4
  #       with:
  #         repository: 'webdriverio/native-demo-app'

  #     - name: Setup env
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '>=18.x'

  #     - uses: actions/setup-java@v4
  #       with:
  #         distribution: 'adopt-hotspot'
  #         java-version: '17'

  #     - name: Install packages
  #       run: |
  #         npm install

  #     - name: Build apk
  #       run: |
  #         npm run "android.release"
  # test:
  #   runs-on: macos-13

  # steps:
  #   - name: Setup Android SDK
  #     uses: android-actions/setup-android@v2

  #   - name: Create and start emulator
  #     run: |
  #       echo "y" | sdkmanager "platforms;android-30" "system-images;android-30;google_apis;x86_64"
  #       echo "no" | avdmanager create avd --force --name nightwatch-android-11 --device "pixel_xl" --package "system-images;android-30;google_apis;x86_64" --abi "x86_64"
  #       $ANDROID_HOME/emulator/emulator -avd nightwatch-android-11 -no-audio -no-window -no-snapshot -accel on &

  #   - name: Wait for emulator to start
  #     run: |
  #       until adb shell getprop sys.boot_completed | grep 1; do sleep 1; done
  #       adb shell input keyevent 82

  #   - name: Checkout Pet project
  #     uses: actions/checkout@v4

  #   - name: Install packages
  #     run: |
  #       npm ci

  #   # - name: Copy apk
  #   #   run: npm run copy_apk

  #   - name: Run test
  #     run: |
  #       npm run wdio

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./reports
