name: Automation tests

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-13

    steps:
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create and start emulator
        run: |
          # avdmanager list device

          echo "y" | sdkmanager "platforms;android-30" "system-images;android-30;google_apis;x86_64"
          echo "no" | avdmanager create avd --force --name "Nexus_6_API_30" --device "Nexus 6" --package "system-images;android-30;google_apis;x86_64" --abi "x86_64"
          $ANDROID_HOME/emulator/emulator -avd Nexus_6_API_30 -no-audio -no-window -no-snapshot -accel on &

      - name: Wait for emulator to start
        run: |
          until adb shell getprop sys.boot_completed | grep 1; do sleep 1; done
          adb shell input keyevent 82

      - name: Checkout Pet project
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm ci

  #     - name: Run test
  #       run: |
  #         npm run wdio

  deploy:
    # needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/artifacts/allure/source
          gh_pages: gh-pages
          allure_report: build/artifacts/allure/report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
