name: Automation tests

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  # test:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Setup Android SDK
  #       uses: android-actions/setup-android@v2

  # - name: Set up environment variables
  #   run: |
  #     echo "ANDROID_HOME=/Users/runner/Library/Android/sdk" >> $GITHUB_ENV
  #     echo "ANDROID_SDK_ROOT=/Users/runner/Library/Android/sdk" >> $GITHUB_ENV

  # - name: Create and start emulator
  #   run: |
  #     $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
  #     $ANDROID_HOME/platform-tools/adb shell input keyevent 82

  # - name: Create and start emulator
  #   run: |
  #     echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "system-images;android-30;google_apis;x86_64"
  #     echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force --name testEmulator --device "Nexus 5" --package "system-images;android-30;google_apis;x86_64" --abi "x86_64"
  #     $ANDROID_HOME/emulator/emulator -avd testEmulator -no-audio -no-window -no-snapshot -accel on &
  #     $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
  #     $ANDROID_HOME/platform-tools/adb shell input keyevent 82

  # - name: Checkout Pet project
  # uses: actions/checkout@v4

  # - name: Install packages
  #   run: |
  #     npm ci

  # - name: Run test
  #   run: |
  #     npm run wdio

  deploy:
    # needs: test
    runs-on: ubuntu-latest

    steps:
      # - name: Download artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: artifacts

      - name: Checkout Pet project
        uses: actions/checkout@v4
        with:
          ref: actions

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        # id: allure-report
        with:
          allure_results: build/artifacts/allure/source
          gh_pages: gh-pages
          allure_report: build/artifacts/allure/report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      # - name: Test marketplace action
      #   uses: simple-elf/allure-report-action@master
      #   if: always()
      #   id: allure-report
      #   with:
      #     allure_results: build/artifacts/allure/source
      #     gh_pages: gh-pages
      #     allure_report: build/artifacts/allure/report
      #     allure_history: allure-history

      # - name: Deploy 🚀  THIS WORK
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: artifacts
